# Correlation Between Video Game Critic Review Scores and Global Sales

#### Purpose: A video game publisher would like to better understand if critic review scores are associated with sales. The analysis will examine if higher critic review scores correlate with higher global sales and if the relationship is statistically significant. The results may help the organization evaluate the usefulness of critic reviews as an indicator of market performance.

H₀: There is no statistically significant correlation between video game critic review scores and global sales.

Hₐ: There is a statistically significant correlation between video game critic review scores and global sales.

#### 1. Data Extraction

In [3]:
# imports
import pandas as pd
import numpy as np

In [4]:
# read in data
df = pd.read_csv('video_games_sales.csv', sep=';')
df.sample(5)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating,Unnamed: 16,Unnamed: 17
10581,Disney's The Haunted Mansion,GC,2003,Platform,Take-Two Interactive,"0,08","0,02",0,0,"0,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12957,Nobunaga's Ambition: Sphere of Influence,PSV,2014,Strategy,Tecmo Koei,0,0,"0,05",0,"0,05",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3248,Bass Landing,PS,1999,Sports,ASCII Entertainment,"0,21","0,14","0,23","0,04","0,62",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5942,Dreamworks Madagascar Kartz,PS3,2009,Racing,Activision,"0,19","0,07",0,"0,04","0,29",NaN,NaN,tbd,NaN,Sidhe Interactive,E,NaN,NaN
4822,Rampage: Total Destruction,GC,2006,Action,Midway Games,"0,31","0,08",0,"0,01","0,4",57,24,"6,7",6,"Pipeworks Software, Inc.",E10+,NaN,NaN

In [6]:
# take a look at the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16693 non-null  object
 2   Year_of_Release  16426 non-null  object
 3   Genre            16689 non-null  object
 4   Publisher        16640 non-null  object
 5   NA_Sales         16692 non-null  object
 6   EU_Sales         16693 non-null  object
 7   JP_Sales         16693 non-null  object
 8   Other_Sales      16693 non-null  object
 9   Global_Sales     16693 non-null  object
 10  Critic_Score     8215 non-null   object
 11  Critic_Count     8160 non-null   object
 12  User_Score       10011 non-null  object
 13  User_Count       7594 non-null   object
 14  Developer        10084 non-null  object
 15  Rating           9946 non-null   object
 16  Unnamed: 16      33 non-null     object
 17  Unnamed: 17      2 non-null      object
dtypes: object(18)
memory usage: 2.3+ MB

In [ ]:
'''
Workflow list:
1. delete Unnamed 16 and 17
2. Global Sales entry formatting
3. Narrow entries to those with critic scores
4. Possibly get rid of the two rows with no game name
5. Change data types to be usable
'''

#### 2. Transform

In [7]:
# There are two extra columns that read in that should not be there. Drop columns
df = df.drop(columns=['Unnamed: 16', 'Unnamed: 17'])

In [8]:
# Check
df.head(2)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006,Sports,Nintendo,"41,36","28,96","3,77","8,45","82,53",76,51,8,322,Nintendo,E
1,Super Mario Bros.,NES,1985,Platform,Nintendo,"29,08","3,58","6,81","0,77","40,24",NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#